[project]
name = "notifications-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.5",
    "fastapi[standard]>=0.139.0",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.14.2",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-env>=1.6.0",
    "ruff>=0.16.0",
]

[tool.fastapi]
entrypoint = "app.main:app"

[tool.pytest_env]
env_files = [".env.test"]

[tool.ruff]
indent-width = 4
unsafe-fixes = false
fix = true

[tool.ruff.lint]
select = ["ALL"]
logger-objects = []
ignore = [
    "D1", # Allow missing docstrings
    "CPY", # Allow missing copyright notice
    "D213", # multi-line-summary-second-line
    "TD002", # missing-todo-author
    "TD003", # missing-todo-link
    "ERA001", # commented-out-code
    "TCH", # Pydantic and SQLAlchemy will require certain types at runtime
    # Prefer Ruff Formatter for handling these rules
    "W191", # tab-indentation
    "E111", # indentation-with-invalid-multiple
    "E114", # indentation-with-invalid-multiple-comment
    "E117", # over-indented
    "D203", # incorrect-blank-line-before-class
    "D206", # docstring-tab-indentation
    "D300", # triple-single-quotes
    "Q000", # bad-quotes-inline-string
    "Q001", # bad-quotes-multiline-string
    "Q002", # bad-quotes-docstring
    "Q003", # avoidable-escaped-quote
    "Q004", # unnecessary-escaped-quote
    "COM812", # missing-trailing-comma
    "COM819", # prohibited-trailing-comma
    "ISC002", # multi-line-implicit-string-concatenation
]

[tool.ruff.lint.per-file-ignores]
"app/main.py" = [
    "ANN201", # No need to specify return types in the app entry point
]
"app/**router.py" = [
    "ANN201", # No need to specify return types for routers in their function signature
]
"tests/**.py" = [
    "ANN001", # No need to specify types for function arguments in test files
    "ANN2", # No need to specify return types in test files
    "S101", # Allow asserts in test files
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    "PLR2004", # Allow magic values for comparisons in test files
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
]
"alembic/**.py" = [
    "D", # Do not enforce documentation rules on autogenerated files
    "INP001", # Allow implicit namespace packages for alembic
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

