version: 2.1

orbs:
  python: circleci/python@4.0.0
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.14.6
      - image: cimg/postgres:18.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: challenge_db_test
    executor:
      name: python/default
      tag: '3.14'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - run:
          command: |
            uv run pytest --cov=app --cov-report term-missing --cov-report lcov tests/ -v
          name: Test it
          environment:
            DATABASE_PROTOCOL_DRIVER: postgresql+psycopg
            DATABASE_HOST: 127.0.0.1
            DATABASE_PORT: 5432
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_NAME: challenge_db_test
      - coveralls/upload:
          debug: true
          coverage_file: ./coverage.lcov
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test:
    jobs:
      - build_and_test
