"""Add push notification token column to Users table

Revision ID: 8d90ce55be01
Revises: a6fbd5be7713
Create Date: 2026-08-06 04:11:05.624020

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d90ce55be01"
down_revision: str | Sequence[str] | None = "a6fbd5be7713"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("push_token", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "push_token")
    # ### end Alembic commands ###
