"""add status column to notifications table

Revision ID: a6fbd5be7713
Revises: 92330c5c0421
Create Date: 2026-08-02 02:53:17.272111

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6fbd5be7713"
down_revision: str | Sequence[str] | None = "92330c5c0421"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

status_enum = sa.Enum("PENDING", "SENT", "FAILED", name="notification_status")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind())
    op.add_column(
        "notifications",
        sa.Column(
            "status",
            status_enum,
            server_default="PENDING",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "status")
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
